updated manifest

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -73,82 +73,81 @@ jobs:
   #         docker push ${{ secrets.DOCKERHUB_USERNAME }}/result-app:${{ github.run_number }}
 
  
-  trivy_scan:
-    name: Scan Docker Images for Vulnerabilities
-    runs-on: ubuntu-latest
-    #needs: [docker_build]
+  # trivy_scan:
+  #   name: Scan Docker Images for Vulnerabilities
+  #   runs-on: ubuntu-latest
+  #   #needs: [docker_build]
 
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v2
+  #   steps:
+  #     - name: Check out code
+  #       uses: actions/checkout@v2
 
-          # Cache Trivy installation
-      - name: Cache Trivy installation
-        uses: actions/cache@v3
-        with:
-          path: ~/.cache/trivy
-          key: trivy-${{ runner.os }}-v0.43.0
-          restore-keys: |
-            trivy-${{ runner.os }}-
+  #         # Cache Trivy installation
+  #     - name: Cache Trivy installation
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: ~/.cache/trivy
+  #         key: trivy-${{ runner.os }}-v0.43.0
+  #         restore-keys: |
+  #           trivy-${{ runner.os }}-
+ 
+  #     - name: Install Trivy
+  #       run: |
+  #         if [ ! -d "$HOME/.cache/trivy" ]; then
+  #           echo "Installing Trivy version v0.43.0..."
+  #           wget https://github.com/aquasecurity/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.deb
+  #           sudo dpkg -i trivy_0.43.0_Linux-64bit.deb
+  #         else
+  #           echo "Trivy found in cache."
+  #         fi
+  #           trivy --version  # Verify Trivy installation
 
-      
-      - name: Install Trivy
-        run: |
-          if [ ! -d "$HOME/.cache/trivy" ]; then
-            echo "Installing Trivy version v0.43.0..."
-            wget https://github.com/aquasecurity/trivy/releases/download/v0.43.0/trivy_0.43.0_Linux-64bit.deb
-            sudo dpkg -i trivy_0.43.0_Linux-64bit.deb
-          else
-            echo "Trivy found in cache."
-          fi
-            trivy --version  # Verify Trivy installation
-
-       # Cache Docker image scan results based on image hash
-      - name: Cache Docker scan results
-        uses: actions/cache@v3
-        with:
-          path: ~/.cache/trivy/results
-          key: trivy-scan-${{ secrets.VOTING_APP_IMAGE }}-${{ secrets.RESULT_APP_IMAGE }}-${{ secrets.WORKER_APP_IMAGE }}-${{ github.sha }}
-          restore-keys: |
-            trivy-scan-
+  #      # Cache Docker image scan results based on image hash
+  #     - name: Cache Docker scan results
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: ~/.cache/trivy/results
+  #         key: trivy-scan-${{ secrets.VOTING_APP_IMAGE }}-${{ secrets.RESULT_APP_IMAGE }}-${{ secrets.WORKER_APP_IMAGE }}-${{ github.sha }}
+  #         restore-keys: |
+  #           trivy-scan-
     
-       # Step to scan Docker images
-      - name: Scan Docker image with Trivy
-        run: |
-          echo "#####################
-          Scanning VOTING APP image for vulnerabilities...
-          ##############################"
+  #      # Step to scan Docker images
+  #     - name: Scan Docker image with Trivy
+  #       run: |
+  #         echo "#####################
+  #         Scanning VOTING APP image for vulnerabilities...
+  #         ##############################"
 
-          attempts=0
-          max_attempts=5
-          until trivy image --severity HIGH,CRITICAL --format table ${{ secrets.VOTING_APP_IMAGE }} || [ $attempts -eq $max_attempts ]; do
-            echo "Retrying scan... attempt $((attempts+1))"
-            attempts=$((attempts+1))
-            sleep 10  # Delay before retry
-          done
-          if [ $attempts -eq $max_attempts ]; then
-            echo "Failed to complete the scan after $max_attempts attempts."
-            exit 1
-          fi
+  #         attempts=0
+  #         max_attempts=5
+  #         until trivy image --severity HIGH,CRITICAL --format table ${{ secrets.VOTING_APP_IMAGE }} || [ $attempts -eq $max_attempts ]; do
+  #           echo "Retrying scan... attempt $((attempts+1))"
+  #           attempts=$((attempts+1))
+  #           sleep 10  # Delay before retry
+  #         done
+  #         if [ $attempts -eq $max_attempts ]; then
+  #           echo "Failed to complete the scan after $max_attempts attempts."
+  #           exit 1
+  #         fi
 
-          #trivy image --severity HIGH,CRITICAL --format table ${{ secrets.VOTING_APP_IMAGE }}
+  #         #trivy image --severity HIGH,CRITICAL --format table ${{ secrets.VOTING_APP_IMAGE }}
 
-          echo "#########################
-          Scanning RESULT APP image for vulnerabilities...
-          ######################"
+  #         echo "#########################
+  #         Scanning RESULT APP image for vulnerabilities...
+  #         ######################"
 
-          trivy image --severity HIGH,CRITICAL --format table ${{ secrets.RESULT_APP_IMAGE }}
+  #         trivy image --severity HIGH,CRITICAL --format table ${{ secrets.RESULT_APP_IMAGE }}
 
-          echo "###################
-          Scanning WORKER APP image for vulnerabilities...
-          #########################"
+  #         echo "###################
+  #         Scanning WORKER APP image for vulnerabilities...
+  #         #########################"
 
-          trivy image --severity HIGH,CRITICAL --format table ${{ secrets.WORKER_APP_IMAGE }}
+  #         trivy image --severity HIGH,CRITICAL --format table ${{ secrets.WORKER_APP_IMAGE }}
 
 
   deploy:
     runs-on: ubuntu-latest
-    needs: trivy_scan
+    #needs: trivy_scan
     strategy:
       matrix:
         region: [us-west-2, eu-west-1]
