updated pipeline

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -119,7 +119,19 @@ jobs:
           Scanning VOTING APP image for vulnerabilities...
           ##############################"
 
-          trivy image --severity HIGH,CRITICAL --format table ${{ secrets.VOTING_APP_IMAGE }}
+          attempts=0
+          max_attempts=5
+          until trivy image --severity HIGH,CRITICAL --format table ${{ secrets.VOTING_APP_IMAGE }} || [ $attempts -eq $max_attempts ]; do
+            echo "Retrying scan... attempt $((attempts+1))"
+            attempts=$((attempts+1))
+            sleep 10  # Delay before retry
+          done
+          if [ $attempts -eq $max_attempts ]; then
+            echo "Failed to complete the scan after $max_attempts attempts."
+            exit 1
+          fi
+          
+          #trivy image --severity HIGH,CRITICAL --format table ${{ secrets.VOTING_APP_IMAGE }}
 
           echo "#########################
           Scanning RESULT APP image for vulnerabilities...
